name: Server

on:
  workflow_dispatch:
  
jobs:
  launch:
    name: Launch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '20'
      - run: dpkg --print-architecture
      - run: sudo chmod 777 ./frpc -f v4y6pnjelz38oxc2:14267195
      - run: java -jar server.jar
