name: Server

on:
  workflow_dispatch:
  
jobs:
  launch:
    name: Launch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '20'
      - run: 
          chmod -R 777 .
      - run:
          ./frpc -f v4y6pnjelz38oxc2:14269791,14269767 &
          ./run.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change
          file_pattern: ./*
          repository: .
          commit_user_name: Poteitou57
          commit_user_email: 412155684@qq.com
          commit_author: Poteitou57
